FROM python:3.9.18-alpine

WORKDIR /src

COPY ./listingsData.py ./scraper.py ./requirements.txt /src/

RUN pip install -r requirements.txt --no-cache-dir

ENTRYPOINT [ "python3", "/src/listingsData.py" ]