FROM python:3.9.18-alpine

ENV APP_HOME /app

WORKDIR $APP_HOME

COPY . .

RUN pip install -r requirements.txt --no-cache-dir

CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 main:app