apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: my-cluster-secret
spec:
  provider:
    gcpsm:
      projectID: proyectopde
      auth:
        workloadIdentity:
          clusterLocation: 	us-central1-a
          clusterName: airflow-cluster
          clusterProjectID: proyectopde
          serviceAccountRef:
            name: airflow-sa
            namespace: external-secrets