apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: airflow-secrets
spec:
  provider:
    gcpsm:
      projectID: proyectopde
      auth:
        workloadIdentity:
          clusterLocation: us-central1-b
          clusterName: airflow-cluster
          clusterProjectID: proyectopde
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets