apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-conn
  namespace: airflow
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: airflow-secrets              
  target:
    name: airflow-db
    creationPolicy: Owner
  data:
  - secretKey: connection
    remoteRef:
      key: db-conn