apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-secret
  namespace: airflow
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: airflow-secrets              
  target:
    name: git-secret
    creationPolicy: Owner
  data:
  - secretKey: gitSshKey 
    remoteRef:
      key: git-secret