apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: my-cluster-secret              
  target:
    name: secret-to-be-created  
    creationPolicy: Owner
  data:
  - secretKey: supersecret  
    remoteRef:
      key: supersecret
