apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: webserver-key
  namespace: airflow
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: airflow-secrets              
  target:
    name: webserver-key
    creationPolicy: Owner
  data:
  - secretKey: webserver-secret-key
    remoteRef:
      key: webserver-key